import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import fastifyStatic from '@fastify/static';
import { Server as SocketServer } from 'socket.io';
import { randomBytes } from 'node:crypto';
import path from 'node:path';
import { RoomStore } from './rooms.js';

const port=Number(process.env.PORT??3000);const isProduction=process.env.NODE_ENV==='production';
const app=Fastify({logger:true,bodyLimit:16_384});await app.register(cookie);
app.addHook('onRequest',async(req,reply)=>{if(isProduction&&req.method!=='GET'&&req.method!=='HEAD'){const origin=req.headers.origin;if(origin!==`https://${req.headers.host}`)return reply.code(403).send({error:'ORIGIN_REJECTED'})}});
app.addHook('onSend',async(_req,reply,payload)=>{reply.header('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' ws: wss:; font-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");reply.header('X-Content-Type-Options','nosniff');reply.header('Referrer-Policy','same-origin');return payload});
const dist=path.resolve(process.cwd(),'dist/web');
await app.register(fastifyStatic,{root:dist,prefix:'/sequence/'});
const store=new RoomStore(process.env.DATA_FILE);

function guest(req:any,reply:any){let id=req.cookies.sequence_guest as string|undefined;if(!id){id=randomBytes(18).toString('base64url');reply.setCookie('sequence_guest',id,{path:'/sequence/',httpOnly:true,sameSite:'lax',secure:isProduction,maxAge:30*24*3600});}return id;}
function profile(req:any){const raw=typeof req.body?.name==='string'?req.body.name:'Player';const name=raw.normalize('NFC').trim().replace(/\s+/g,' ');const length=[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(name)].length;const hasControl=[...name].some(char=>{const code=char.charCodeAt(0);return code<32||code===127});if(!name||length>24||hasControl)throw new Error('INVALID_NAME');const avatarId=typeof req.body?.avatarId==='string'?req.body.avatarId:'avataaars-01';const match=/^avataaars-(\d{2})$/.exec(avatarId);if(!match||Number(match[1])<1||Number(match[1])>24)throw new Error('INVALID_AVATAR');return{name,avatarId};}
function response(room:any,gid:string){return store.snapshot(room,gid);}
function fail(reply:any,e:unknown){const code=e instanceof Error?e.message:'UNKNOWN';return reply.code(['ROOM_NOT_FOUND'].includes(code)?404:409).send({error:code,message:code.replaceAll('_',' ').toLowerCase()});}
function broadcast(room:any){for(const m of room.members)io.to(`guest:${m.guestId}`).emit('snapshot',response(room,m.guestId));}

app.get('/',async(_,reply)=>reply.type('text/html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>Childrex</title><style>body{margin:0;background:#14161a;color:#e9eaee;font-family:system-ui;display:grid;place-items:center;min-height:100vh}main{text-align:center}a{display:inline-block;margin-top:18px;padding:14px 22px;background:#ffc53d;color:#1d1f3a;border-radius:14px;text-decoration:none;font-weight:700}</style></head><body><main><h1>Childrex</h1><p>Play a game with friends.</p><a href="/sequence/">Play Sequence</a></main></body></html>'));
app.get('/sequence',async(_,reply)=>reply.redirect('/sequence/'));
app.post('/sequence/api/session',async(req:any,reply)=>{const gid=guest(req,reply);return{guestId:gid,room:store.roomForGuest(gid)?response(store.roomForGuest(gid)!,gid):null};});
app.post('/sequence/api/rooms',async(req:any,reply)=>{try{const gid=guest(req,reply);const p=profile(req);const room=store.create(gid,p.name,p.avatarId);store.persist();return response(room,gid);}catch(e){return fail(reply,e);}});
app.post('/sequence/api/rooms/lookup',async(req:any)=>{const code=String(req.body?.code??'');if(!/^\d{2}$/.test(code))return{found:false};const room=store.lookup(code);return room?{found:true,joinable:room.phase==='lobby'&&room.seats.length<12,count:room.seats.length}:{found:false};});
app.post('/sequence/api/rooms/join',async(req:any,reply)=>{try{const gid=guest(req,reply);const p=profile(req);const code=String(req.body?.code??'');if(!/^\d{2}$/.test(code))throw new Error('ROOM_NOT_FOUND');const room=store.join(code,gid,p.name,p.avatarId);store.persist();broadcast(room);return response(room,gid);}catch(e){return fail(reply,e);}});
app.get('/sequence/api/rooms/:id',async(req:any,reply)=>{try{const gid=guest(req,reply);const room=store.rooms.get(req.params.id);if(!room)throw new Error('ROOM_NOT_FOUND');store.member(room,gid);return response(room,gid);}catch(e){return fail(reply,e);}});
app.post('/sequence/api/commands',async(req:any,reply)=>{try{const gid=guest(req,reply);const b=req.body??{};const room=store.rooms.get(b.roomId);if(!room)throw new Error('ROOM_NOT_FOUND');if(b.commandId&&room.receipts.has(`${gid}:${b.commandId}`))return room.receipts.get(`${gid}:${b.commandId}`);let result;switch(b.type){case'addComputer':result=store.addComputer(room,gid,b.teamId);break;case'addTeam':result=store.addTeam(room,gid);break;case'removeComputer':result=store.removeComputer(room,gid,b.seatId);break;case'moveSeat':result=store.moveSeat(room,gid,b.seatId,b.teamId);break;case'setColor':result=store.setColor(room,gid,b.teamId,b.color);break;case'start':result=store.start(room,gid);break;case'play':result=store.play(room,gid,b.cardId,b.row,b.col);break;case'exchange':result=store.exchange(room,gid,b.cardId);break;case'pass':result=store.pass(room,gid);break;case'replay':result=store.replay(room,gid);break;case'profile':{const p=profile({body:b});result=store.updateProfile(room,gid,p.name,p.avatarId);break}default:throw new Error('UNKNOWN_COMMAND');}const out=response(result,gid);if(b.commandId)room.receipts.set(`${gid}:${b.commandId}`,out);store.persist();broadcast(room);return out;}catch(e){return fail(reply,e);}});
app.get('/sequence/api/health/live',async()=>({ok:true}));
app.get('/sequence/api/version',async()=>({sha:process.env.BUILD_SHA??'dev'}));
if(process.env.NODE_ENV==='test')app.post('/sequence/api/test/fixture',async(req:any,reply)=>{try{const gid=guest(req,reply);const room=store.rooms.get(req.body?.roomId);if(!room?.round)throw new Error('NO_ROUND');store.member(room,gid);const kind=String(req.body?.kind);const team=room.teams[0];const cells=Array.from({length:5},(_,col)=>({row:4,col:col+1}));for(const cell of cells)room.round.chips[cell.row][cell.col]=team.id;room.round.sequences=[{id:'fixture-sequence',teamId:team.id,cells,createdTurn:room.round.turn}];room.round.lastMove={seatId:team.seatIds[0],teamId:team.id,kind:'place',cell:cells[4],cardFace:'JC',turn:room.round.turn};if(kind==='win'){room.round.result={winnerTeamId:team.id,reason:'sequences'};room.round.currentSeatIndex=null;room.phase='finished'}room.version++;broadcast(room);return response(room,gid)}catch(e){return fail(reply,e)}});
app.setNotFoundHandler(async(req,reply)=>{if(req.url.startsWith('/sequence/api/')||req.url.includes('.'))return reply.code(404).send({error:'NOT_FOUND'});return reply.sendFile('index.html');});

const io=new SocketServer(app.server,{path:'/sequence/socket.io',cors:{origin:false}});
const takeoverTimers=new Map<string,NodeJS.Timeout>();
io.on('connection',socket=>{const raw=socket.handshake.headers.cookie??'';const gid=raw.split(';').map(s=>s.trim()).find(s=>s.startsWith('sequence_guest='))?.split('=')[1];if(!gid){socket.disconnect();return;}socket.join(`guest:${gid}`);const room=store.roomForGuest(gid);if(room){const m=room.members.find(m=>m.guestId===gid);if(m){m.connected=true;const seat=room.seats.find(s=>s.id===m.seatId);if(seat){seat.computer=false;const roundSeat=room.round?.seats.find(s=>s.id===seat.id);if(roundSeat)roundSeat.computer=false}}const timer=takeoverTimers.get(gid);if(timer)clearTimeout(timer);takeoverTimers.delete(gid);socket.emit('snapshot',response(room,gid));broadcast(room);}socket.on('disconnect',()=>{const r=store.roomForGuest(gid);const m=r?.members.find(m=>m.guestId===gid);if(!r||!m)return;m.connected=false;broadcast(r);const timer=setTimeout(()=>{const current=store.roomForGuest(gid);const member=current?.members.find(x=>x.guestId===gid);if(!current||!member||member.connected)return;const seat=current.seats.find(s=>s.id===member.seatId);if(current.phase==='playing'&&seat){seat.computer=true;const roundSeat=current.round?.seats.find(s=>s.id===seat.id);if(roundSeat)roundSeat.computer=true;if(current.hostGuestId===gid){const successor=current.members.filter(x=>x.connected).sort((a,b)=>a.joinedAt-b.joinedAt)[0];if(successor)current.hostGuestId=successor.guestId}store.runComputers(current);store.persist();broadcast(current)}takeoverTimers.delete(gid)},30_000);takeoverTimers.set(gid,timer)});});

await app.listen({port,host:'0.0.0.0'});
