import { describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { RoomStore } from './rooms';

function ready(){const store=new RoomStore();const room=store.create('host','Host','avataaars-01');store.join(room.code,'guest','Guest','avataaars-02');store.setColor(room,'host',room.teams[0].id,'blue');store.setColor(room,'host',room.teams[1].id,'red');return{store,room}}

describe('room authorization and privacy',()=>{
  it('allocates an exact two-digit code',()=>{const room=new RoomStore().create('host','Host','avataaars-01');expect(room.code).toMatch(/^\d{2}$/)});
  it('releases the invite code as soon as the game starts',()=>{const {store,room}=ready();const code=room.code;store.start(room,'host');expect(store.lookup(code)).toBeUndefined()});
  it('recycles the earliest waiting code after all 99 codes are occupied',()=>{const store=new RoomStore();const first=store.create('guest-0','Player 0','avataaars-01');first.createdAt=0;for(let index=1;index<99;index++)store.create(`guest-${index}`,`Player ${index}`,'avataaars-01');const replacement=store.create('guest-99','Player 99','avataaars-01');expect(first.code).toBe('');expect(replacement.code).toMatch(/^\d{2}$/);expect(store.byCode.size).toBe(99)});
  it('refuses non-host configuration and start commands',()=>{const {store,room}=ready();expect(()=>store.addComputer(room,'guest',room.teams[0].id)).toThrow('NOT_HOST');expect(()=>store.start(room,'guest')).toThrow('NOT_HOST')});
  it('does not disclose another player hand or deck in personalized snapshots',()=>{const {store,room}=ready();store.start(room,'host');const host=store.snapshot(room,'host');const guest=store.snapshot(room,'guest');expect(host.yourHand).toHaveLength(7);expect(guest.yourHand).toHaveLength(7);expect(host.yourHand).not.toEqual(guest.yourHand);expect(JSON.stringify(host)).not.toContain(guest.yourHand[0].id);expect(host.round).not.toHaveProperty('drawPile');expect(host.round).not.toHaveProperty('hands')});
  it('requires membership before returning a member or acting',()=>{const {store,room}=ready();expect(()=>store.member(room,'stranger')).toThrow('NOT_MEMBER');expect(()=>store.play(room,'stranger','x',1,1)).toThrow('NOT_MEMBER')});
  it('balances joined humans onto opposite teams',()=>{const {room}=ready();expect(room.teams.map(t=>t.seatIds.length)).toEqual([1,1])});
  it('removes a lobby guest and releases their room membership',()=>{const {store,room}=ready();store.leave(room,'guest');expect(room.members).toHaveLength(1);expect(room.seats).toHaveLength(1);expect(store.roomForGuest('guest')).toBeUndefined()});
  it('hands an active departed seat to a computer without exposing it to the guest',()=>{const {store,room}=ready();store.start(room,'host');const seatId=store.member(room,'guest').seatId;store.leave(room,'guest');expect(room.seats.find(seat=>seat.id===seatId)?.computer).toBe(true);expect(store.snapshot(room,'guest').yourHand).toHaveLength(0)});
  it('expires an active room after its final human leaves',()=>{const {store,room}=ready();store.start(room,'host');store.leave(room,'guest');store.leave(room,'host');expect(store.lookup(room.code)).toBeUndefined();expect(store.roomForGuest('host')).toBeUndefined()});
  it('switches rooms only after validating the target lobby',()=>{const store=new RoomStore();const first=store.create('one','One','avataaars-01');const second=store.create('two','Two','avataaars-02');store.join(second.code,'one','One','avataaars-01');expect(store.roomForGuest('one')?.id).toBe(second.id);expect(first.members).toHaveLength(0);expect(second.members).toHaveLength(2)});
  it('assigns the unused color when a selected two-team lobby adds a third team',()=>{const {store,room}=ready();store.addTeam(room,'host');expect(room.teams[2].color).toBe('green')});
  it('uses the green add-team affordance when colors have not been selected yet',()=>{const store=new RoomStore();const room=store.create('host','Host','avataaars-01');store.addTeam(room,'host');expect(room.teams[2]).toMatchObject({id:'team-green',color:'green',seatIds:[]})});
  it('only removes an empty team',()=>{const {store,room}=ready();store.addTeam(room,'host');store.addComputer(room,'host',room.teams[2].id);expect(()=>store.removeTeam(room,'host',room.teams[2].id)).toThrow('TEAM_NOT_EMPTY');store.removeComputer(room,'host',room.teams[2].seatIds[0]);store.removeTeam(room,'host',room.teams[2].id);expect(room.teams.map(team=>team.id)).toEqual(['team-blue','team-red'])});
  it('freezes team colors after a round starts',()=>{const {store,room}=ready();store.start(room,'host');expect(()=>store.setColor(room,'host',room.teams[0].id,'green')).toThrow('ROUND_STARTED')});
  it('runs exactly one complete computer turn at a time',()=>{const store=new RoomStore();const room=store.create('host','Host','avataaars-01');store.addComputer(room,'host',room.teams[1].id);store.setColor(room,'host',room.teams[0].id,'blue');store.setColor(room,'host',room.teams[1].id,'red');store.start(room,'host');if(room.round?.currentSeatIndex===0){const action=store.snapshot(room,'host').yourActions.find(candidate=>candidate.cells.length);store.play(room,'host',action!.cardId,action!.cells[0].row,action!.cells[0].col)}const before=room.round!.turn;expect(store.computerTurn(room)).toBe(true);expect(room.round!.turn).toBe(before+1);expect(store.computerTurn(room)).toBe(false)});
  it('returns the same people, computers, teams, and colors to a configurable lobby',()=>{const store=new RoomStore();const room=store.create('host','Host','avataaars-01');store.addComputer(room,'host',room.teams[1].id);store.setColor(room,'host',room.teams[0].id,'blue');store.setColor(room,'host',room.teams[1].id,'red');const before={teams:structuredClone(room.teams),seats:structuredClone(room.seats),members:structuredClone(room.members)};store.start(room,'host');store.newGame(room,'host');expect(room.phase).toBe('lobby');expect(room.round).toBeNull();expect(room.teams).toEqual(before.teams);expect(room.seats).toEqual(before.seats);expect(room.members).toEqual(before.members);expect(store.lookup(room.code)).toBe(room)});
  it('restores acknowledged room and round state after a process restart without reopening its code',()=>{const dir=mkdtempSync(path.join(tmpdir(),'sequence-store-'));try{const file=path.join(dir,'rooms.json');const first=new RoomStore(file);const room=first.create('host','Host','avataaars-01');first.addComputer(room,'host',room.teams[1].id);first.setColor(room,'host',room.teams[0].id,'blue');first.setColor(room,'host',room.teams[1].id,'red');first.start(room,'host');first.persist();const version=room.version;const second=new RoomStore(file);const restored=second.rooms.get(room.id);expect(second.lookup(room.code)).toBeUndefined();expect(restored?.version).toBe(version);expect(restored?.round?.hands[room.seats[0].id]).toHaveLength(7)}finally{rmSync(dir,{recursive:true,force:true})}});
});
