import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, Heart, LogOut, Menu as MenuIcon, Plus, Play, RotateCcw, Sparkles, Spade, User, Users, Volume2, X } from 'lucide-react';
import { BOARD, toDisplay, toLogical } from '../../../packages/engine/src/board';
import type { CardFace, Cell, Seat, Team, TeamColor } from '../../../packages/engine/src/types';
import { api, connect } from './api';
import { cues } from './audio';
import type { RoomLookup, RoomSnapshot, Selected } from './types';

const COLORS: TeamColor[]=['blue','red','green'];
const COLOR_HEX:Record<TeamColor,string>={blue:'#2F6BFF',red:'#E5484D',green:'#30A46C'};
const avatar=(id:string)=>`/sequence/assets/avatars/${id}.svg`;
const card=(face:CardFace)=>`/sequence/assets/cards/${face}.svg`;
const cellKey=(cell:Cell)=>`${cell.row},${cell.col}`;

function Logo(){return <div className="brand" aria-label="Sequence">SEQUENCE</div>}
function Spinner(){return <div className="loading"><span/><p>Setting the table…</p></div>}
function Credits(){return <main className="credits-shell"><a className="credits-back" href="/sequence/">← Back to game</a><Logo/><p className="eyebrow">CREDITS &amp; LICENSES</p><h1>Made for the table.</h1><p className="credits-intro">The game keeps its visual assets local, so cards and avatars remain fast and dependable during play.</p><section><h2>Playing cards</h2><p>The card artwork comes from the Public Domain Deck and is provided under CC0 1.0.</p><a href="https://github.com/AustinGabriel/The-Public-Domain-Deck-Public-Domain-and-CC0-Playing-Cards" target="_blank" rel="noreferrer">View the source deck</a></section><section><h2>Avatars</h2><p>Avataaars was created by Pablo Stanley. These local SVG variations were generated with DiceBear, distributed under the MIT license.</p><a href="https://www.dicebear.com/styles/avataaars/" target="_blank" rel="noreferrer">About Avataaars</a></section><section><h2>Type</h2><p>Jost and Manrope are distributed through Fontsource under their upstream SIL Open Font License terms.</p></section><small>This independent browser game is not affiliated with the commercial Sequence product owner.</small></main>}

function Avatar({id,name,editable=false,onClick}:{id:string;name:string;editable?:boolean;onClick?:()=>void}){
  const content=<img src={avatar(id)} alt=""/>;
  return editable?<button className="avatar avatar-button" onClick={event=>{event.stopPropagation();onClick?.()}} aria-label={`Change ${name}'s avatar`}>{content}</button>:<span className="avatar">{content}</span>;
}

function AvatarPicker({current,onSelect,onClose}:{current:string;onSelect:(id:string)=>void;onClose:()=>void}){
  return <div className="scrim" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>
    <section className="dialog avatar-dialog" role="dialog" aria-modal="true" aria-labelledby="avatar-title">
      <button className="close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">PROFILE</p><h2 id="avatar-title">Choose your avatar</h2>
      <div className="avatar-grid">{Array.from({length:24},(_,i)=>`avataaars-${String(i+1).padStart(2,'0')}`).map((id,i)=><button key={id} className={id===current?'avatar-option selected':''} aria-label={`Avatar ${i+1}`} aria-pressed={id===current} onClick={()=>onSelect(id)}><img src={avatar(id)} alt=""/></button>)}</div>
    </section>
  </div>
}

function PlayerRow({seat,team,you,current,lobby=false,status,onAvatar,onName,onRemove,onMove}:{seat:Seat;team:Team;you:boolean;current?:boolean;lobby?:boolean;status?:string;onAvatar?:()=>void;onName?:(name:string)=>void;onRemove?:()=>void;onMove?:()=>void}){
  const [editing,setEditing]=useState(false);const [draft,setDraft]=useState(seat.name);const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(editing)input.current?.select()},[editing]);useEffect(()=>setDraft(seat.name),[seat.name]);
  const save=()=>{const name=draft.trim().replace(/\s+/g,' ');if(name&&name.length<=24&&name!==seat.name)onName?.(name);setEditing(false)};
  return <div className={`player ${current?'current':''} ${onMove?'movable':''}`} style={{'--team':team.color?COLOR_HEX[team.color]:'#8B909A'} as React.CSSProperties} title={`${seat.name}${seat.computer?' · Computer':''}${current?' · Current turn':''}`} onClick={onMove}>
    <Avatar id={seat.avatarId} name={seat.name} editable={you} onClick={onAvatar}/>
    <div className="player-copy">{editing?<input ref={input} value={draft} maxLength={24} aria-label="Player name" onClick={e=>e.stopPropagation()} onChange={e=>setDraft(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==='Enter')save();if(e.key==='Escape'){setDraft(seat.name);setEditing(false)}}}/>:<button className="player-name" disabled={!you} onClick={e=>e.stopPropagation()} onDoubleClick={()=>setEditing(true)} onKeyDown={e=>{if((e.key==='Enter'||e.key==='F2')&&you)setEditing(true)}}>{you?'You':seat.name}</button>}<small className={status==='Sequence made'?'status-success':''}>{lobby?(team.color?`${seat.computer?'Computer · ':you?'You · ':''}tap to switch`:'No color selected'):status??(current?(you?'Your turn':'Their turn'):seat.computer?'Computer':team.color?`Team ${team.color[0].toUpperCase()+team.color.slice(1)}`:you?seat.name:'Team member')}</small></div>
    {current&&<span className="turn-dot" aria-label="Current turn"/>}{onRemove&&<button className="remove-player" onClick={event=>{event.stopPropagation();onRemove()}} aria-label={`Remove ${seat.name}`}>×</button>}
    {!lobby&&seat.name.length>14&&<span className="player-tooltip"><i style={{background:team.color?COLOR_HEX[team.color]:'#777'}}/>{seat.name}<small>{team.color?`Team ${team.color[0].toUpperCase()+team.color.slice(1)}`:''}</small></span>}
  </div>
}

function CodeBadge({room,onToast}:{room:RoomSnapshot;onToast:(text:string)=>void}){
  const copy=async()=>{await navigator.clipboard.writeText(`${location.origin}/sequence/join?code=${room.code}&room=${encodeURIComponent(room.id)}`);onToast('Invite copied')};
  return <button className="code-badge" onClick={copy} aria-label={`Copy invite, code ${room.code}`}><small>CODE</small><strong>{room.code}</strong></button>
}

function ColorPicker({team,used,disabled,fallback,count,showCount,onPick}:{team:Team;used:(TeamColor|null)[];disabled:boolean;fallback:TeamColor;count:number;showCount:boolean;onPick:(c:TeamColor)=>void}){
  const available=COLORS.filter(c=>c!==team.color&&!used.includes(c));
  const next=team.color?(available[0]??team.color):(available.includes(fallback)?fallback:(available[0]??fallback));
  return <div className={`color-control ${team.color?'has-color':''} ${team.color&&!available.length?'no-alternative':''}`} style={{'--team':team.color?COLOR_HEX[team.color]:'#9AA0AA'} as React.CSSProperties}>
    <span>{team.color?team.color.toUpperCase():'SELECT COLOR'}</span>{team.color&&showCount&&<small>{count} {count===1?'PLAYER':'PLAYERS'}</small>}
    <button className="color-swatch" disabled={disabled} style={{'--dot':COLOR_HEX[next]} as React.CSSProperties} onClick={()=>onPick(next)} aria-label={`Select ${next}`} />
  </div>
}

function Lobby({room,command,onJoin,onAvatar,onToast}:{room:RoomSnapshot;command:(x:Record<string,unknown>)=>Promise<void>;onJoin:()=>void;onAvatar:()=>void;onToast:(s:string)=>void}){
  const isHost=room.isHost;const sizes=room.teams.map(t=>t.seatIds.length);const balanced=sizes.every(n=>n>0&&n===sizes[0]);const colored=room.teams.every(t=>t.color);const canStart=isHost&&balanced&&colored;
  const capacity=12;const sequences=room.teams.length===3?1:2;
  const shortest=Math.min(...sizes),longest=Math.max(...sizes),shortTeam=room.teams[sizes.indexOf(shortest)];const shortName=shortTeam.color?shortTeam.color[0].toUpperCase()+shortTeam.color.slice(1):'the empty team';const missing=Math.max(1,longest-shortest);const startHint=!isHost?'The host will start when everyone is ready':!colored?'Select a color for each team to continue':!balanced?`Add ${missing} ${missing===1?'player or computer':'players or computers'} to ${shortName}`:'';
  const displayTeams=room.teams.length===3?[room.teams[0],room.teams[2],room.teams[1]]:room.teams;
  return <main className="lobby-shell"><header className="lobby-top"><Logo/><button className="lobby-close" onClick={()=>location.assign('/')} aria-label="Close game"><X size={18}/></button></header>
    <section className="lobby-intro"><div><p className="eyebrow">{room.teams.length} TEAMS · {sequences===1?'FIRST SEQUENCE WINS':'TWO SEQUENCES TO WIN'}</p><h1>Pick your side</h1><p>{colored?(room.teams.length===3?'Tap a player to send them to the next team':'Tap a player to move them across'):'Choose a color for each team'} · {room.seats.length} of {capacity} joined</p></div><CodeBadge room={room} onToast={onToast}/></section>
    <section className={`teams teams-${room.teams.length}`}>{displayTeams.map((team,index)=><article className={`team-panel ${team.color?'selected-team':''}`} key={team.id} style={{'--team':team.color?COLOR_HEX[team.color]:'#8B909A'} as React.CSSProperties}>
      <ColorPicker team={team} used={room.teams.map(t=>t.color)} fallback={team.id==='team-blue'?'blue':team.id==='team-red'?'red':'green'} count={team.seatIds.length} showCount={room.teams.length===3} disabled={!isHost} onPick={color=>command({type:'setColor',teamId:team.id,color})}/>
      <div className="team-players">{team.seatIds.map(seatId=>{const seat=room.seats.find(s=>s.id===seatId)!;const member=room.members.find(m=>m.seatId===seatId);const target=displayTeams[(index+1)%displayTeams.length];return <PlayerRow key={seat.id} seat={seat} team={team} lobby you={member?.isYou??false} onMove={(isHost||member?.isYou)?()=>command({type:'moveSeat',seatId:seat.id,teamId:target.id}):undefined} onAvatar={member?.isYou?onAvatar:undefined} onName={member?.isYou?name=>command({type:'profile',name,avatarId:seat.avatarId}):undefined} onRemove={isHost&&seat.computer?()=>command({type:'removeComputer',seatId:seat.id}):undefined}/>})}</div>
      {isHost&&<button className="subtle-btn" onClick={()=>command({type:'addComputer',teamId:team.id})}><Plus size={18}/>Add computer</button>}
      <button className="subtle-btn" onClick={()=>document.querySelector<HTMLButtonElement>('.code-badge')?.click()}><Plus size={18}/>Invite a friend</button>
      {room.teams.length===3&&index===1&&isHost&&<button className="remove-team" onClick={()=>command({type:'removeTeam',teamId:team.id})}><X size={13}/>Remove team</button>}
    </article>)}
    {room.teams.length===2&&isHost&&<button className="add-team" aria-label="Add third team" onClick={()=>command({type:'addTeam'})}><Plus size={42}/></button>}</section>
    <footer className="lobby-footer"><button className="join-another" onClick={onJoin}><ArrowRight size={20}/>Join another game with code</button><div className="start-wrap"><button className="start" disabled={!canStart} onClick={()=>command({type:'start'})}><Play size={20}/>{!isHost?'Waiting for host':'Start game'}</button>{!canStart&&<small>{startHint}</small>}</div></footer>
  </main>
}

function Corner(){return <svg className="corner-mark" aria-label="Free space" viewBox="0 0 45.2578 45.2578"><circle cx="22.6289" cy="22.6289" r="21.9289" fill="#E8EBEC" stroke="#283239" strokeWidth="1.4"/><circle cx="22.6289" cy="22.6289" r="19.6289" fill="none" stroke="#283239" strokeWidth=".7"/><circle cx="22.6" cy="22.6" r="4" fill="#283239"/><path d="M5 0C3 3 0 4 0 7c0 3 3 4 5 1 2 3 5 2 5-1 0-3-3-4-5-7ZM4 8l-1 4h4L6 8Z" transform="translate(18 5)" fill="#283239"/><path d="M5 12C3 9 0 6 0 3c0-4 4-4 5-1 1-3 5-3 5 1 0 3-3 6-5 9Z" transform="translate(18 29)" fill="#283239"/><path d="m5 0 5 6-5 6-5-6Z" transform="translate(30 17)" fill="#283239"/><path d="M5 0C1 0 1 4 3 5c-4-1-4 5 0 5l2-2-1 4h3L6 8c4 4 6-3 1-3 3-3 1-5-2-5Z" transform="translate(5 17)" fill="#283239"/></svg>}
function Board({room,selected,onPlay}:{room:RoomSnapshot;selected:Selected;onPlay:(cardId:string,cell:Cell)=>void}){
  const round=room.round!;const valid=new Set(selected?.cells.map(cellKey));const sequence=new Set(round.sequences.flatMap(s=>s.cells.map(cellKey)));const last=round.lastMove&&cellKey(round.lastMove.cell);
  return <div className="board-wrap"><div className="board-band board-band-top"><div className="board-rule">• TWO EYED JACKS ARE WILD •</div><div className="board-word">SEQUENCE</div><div className="board-rule">• ONE EYED JACKS REMOVE •</div></div><div className="board-grid" role="grid" aria-label="Sequence board">
    {Array.from({length:10},(_,r)=>Array.from({length:10},(_,c)=>({row:r,col:c}))).flat().map(display=>{const logical=toLogical(display);const face=BOARD[logical.row][logical.col];const key=cellKey(logical);const teamId=round.chips[logical.row][logical.col];const team=room.teams.find(t=>t.id===teamId);const isValid=valid.has(key);return <button key={`${display.row}-${display.col}`} role="gridcell" className={`board-cell ${isValid?'valid':''} ${last===key?'last':''} ${sequence.has(key)?'sequence-cell':''}`} style={{'--chip':team?.color?COLOR_HEX[team.color]:'#777','--valid':selected?colorForSeat(room,room.yourSeatId,true):'transparent'} as React.CSSProperties} disabled={!isValid} onClick={()=>selected&&onPlay(selected.cardId,logical)} aria-label={face==='F'?'Free corner':`${face}${team?' occupied':''}${isValid?' valid move':''}`}>
      {face==='F'?<Corner/>:<img src={card(face)} alt=""/>}{team&&<span className="chip"/>}
    </button>})}
  </div><div className="board-band board-band-bottom"><div className="board-rule">• ONE EYED JACKS REMOVE •</div><div className="board-word">SEQUENCE</div><div className="board-rule">• TWO EYED JACKS ARE WILD •</div></div></div>
}

function colorForSeat(room:RoomSnapshot,seatId:string|null,light=false){const seat=room.seats.find(s=>s.id===seatId);const color=room.teams.find(t=>t.id===seat?.teamId)?.color??'blue';if(!light)return COLOR_HEX[color];return color==='blue'?'#92B5FF':color==='red'?'#FFAFB2':'#8ED9B1'}
function Hand({room,selected,onSelect,onExchange,onPass}:{room:RoomSnapshot;selected:Selected;onSelect:(next:Selected)=>void;onExchange:(id:string)=>void;onPass:()=>void}){
  const yourTurn=room.round?.currentSeatId===room.yourSeatId;const actions=new Map(room.yourActions.map(a=>[a.cardId,a]));
  const selectedAction=selected?actions.get(selected.cardId):undefined;const mustPass=yourTurn&&room.yourActions.length>0&&room.yourActions.every(a=>!a.cells.length)&&(room.round?.exchangeUsed||!room.yourActions.some(a=>a.dead));
  return <div className="hand" style={{'--team':colorForSeat(room,room.yourSeatId)} as React.CSSProperties}><div className={`hand-row ${yourTurn?'':'disabled-hand'}`}>{room.yourHand.map(item=>{const action=actions.get(item.id);const active=selected?.cardId===item.id;return <button key={item.id} disabled={!yourTurn} className={`hand-card ${active?'selected':''} ${action?.dead?'dead':''}`} onClick={()=>onSelect(active?null:action?{cardId:item.id,cells:action.cells,kind:action.kind}:null)} aria-pressed={active}><img src={card(item.face)} alt={item.face}/>{action?.dead&&<span>Dead</span>}</button>})}</div>{selectedAction?.dead&&!room.round?.exchangeUsed&&<button className="hand-action" onClick={()=>onExchange(selectedAction.cardId)}>Replace dead card</button>}{mustPass&&<button className="hand-action" onClick={onPass}>Pass</button>}</div>
}

function Game({room,command,onMenu,onAvatar,menuOpen}:{room:RoomSnapshot;command:(x:Record<string,unknown>)=>Promise<void>;onMenu:()=>void;onAvatar:()=>void;menuOpen:boolean}){
  const [selected,setSelected]=useState<Selected>(null);useEffect(()=>setSelected(null),[room.round?.turn]);const current=room.round?.currentSeatId;
  const play=async(cardId:string,cell:Cell)=>{setSelected(null);await command({type:'play',cardId,row:cell.row,col:cell.col})};
  return <main className="game-shell"><header className="game-top"><Logo/><div className="player-strip">{room.round!.turnOrder.map(id=>{const seat=room.seats.find(s=>s.id===id)!;const team=room.teams.find(t=>t.id===seat.teamId)!;const member=room.members.find(m=>m.seatId===id);const made=room.round!.lastMove?.seatId===id&&room.round!.sequences.some(s=>s.createdTurn===room.round!.lastMove?.turn);const status=room.phase==='finished'?undefined:id===current?undefined:made?'Sequence made':room.round!.lastMove?.seatId===id?'Last move':undefined;return <PlayerRow key={id} seat={seat} team={team} you={member?.isYou??false} current={id===current} status={status} onAvatar={member?.isYou?onAvatar:undefined} onName={member?.isYou?name=>command({type:'profile',name,avatarId:seat.avatarId}):undefined}/>})}</div><button className="menu-btn" aria-expanded={menuOpen} aria-controls="game-menu" onClick={onMenu}><MenuIcon size={16}/>Menu</button></header><Board room={room} selected={selected} onPlay={play}/><Hand room={room} selected={selected} onSelect={setSelected} onExchange={cardId=>command({type:'exchange',cardId})} onPass={()=>command({type:'pass'})}/></main>
}

function Menu({sound,setSound,animations,setAnimations,onClose,onNew,onRules,onLeave}:{sound:boolean;setSound:(v:boolean)=>void;animations:boolean;setAnimations:(v:boolean)=>void;onClose:()=>void;onNew:()=>void;onRules:()=>void;onLeave:()=>void}){useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onClose]);return <div className="scrim menu-scrim" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section id="game-menu" className="menu-popover" role="dialog" aria-modal="true" aria-label="Game menu"><button className="menu-row" onClick={onNew}><RotateCcw/><span>New game</span></button><button className="menu-row" onClick={onRules}><BookOpen/><span>How to play</span><small>?</small></button><i className="menu-divider"/><button className="menu-row" role="switch" aria-checked={sound} onClick={()=>setSound(!sound)}><Volume2/><span>Sound</span><i className={`switch ${sound?'on':''}`}/></button><button className="menu-row" role="switch" aria-checked={animations} onClick={()=>setAnimations(!animations)}><Sparkles/><span>Animations</span><i className={`switch ${animations?'on':''}`}/></button><i className="menu-divider"/><button className="menu-row danger" onClick={onLeave}><LogOut/><span>Leave game</span></button></section></div>}

function RulesDialog({onClose}:{onClose:()=>void}){useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onClose]);return <div className="scrim" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="dialog rules-dialog" role="dialog" aria-modal="true" aria-labelledby="rules-title"><button className="close" onClick={onClose} aria-label="Close"><X size={20}/></button><p className="eyebrow">HOW TO PLAY</p><h2 id="rules-title">Make a sequence of five.</h2><p>Play a card from your hand, then place your team chip on either matching space. Complete five connected chips horizontally, vertically, or diagonally.</p><div className="rule-list"><p><b>Two-eyed Jacks</b><span>Place a chip on any open space.</span></p><p><b>One-eyed Jacks</b><span>Remove one unprotected opponent chip.</span></p><p><b>Free corners</b><span>Count for every team’s sequence.</span></p></div><p className="rules-note">Two teams need two sequences. Three teams need one.</p><a href="/sequence/credits">Credits &amp; licenses</a></section></div>}

function ConfirmDialog({kind,phase,pending,onCancel,onConfirm}:{kind:'new'|'leave';phase:RoomSnapshot['phase'];pending:boolean;onCancel:()=>void;onConfirm:()=>void}){const isNew=kind==='new';useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!pending)onCancel()};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onCancel,pending]);return <div className="scrim"><section className="dialog confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><p className="eyebrow">{isNew?'NEW GAME':'LEAVE GAME'}</p><h2 id="confirm-title">{isNew?'Start a new game?':phase==='lobby'?'Leave this lobby?':'Leave this game?'}</h2><p>{isNew?'You’ll leave this room and get a new invite code.':phase==='lobby'?'You’ll leave this lobby.':`A computer will take your seat for the rest of this round.`}</p><div className="confirm-actions"><button disabled={pending} onClick={onCancel}>Stay</button><button disabled={pending} className={kind==='leave'?'danger-confirm':''} onClick={onConfirm}>{pending?'Working…':isNew?'New game':'Leave'}</button></div></section></div>}

function LeftScreen({onCreate,onJoin}:{onCreate:()=>void;onJoin:()=>void}){return <main className="left-screen"><Logo/><p className="eyebrow">GAME LEFT</p><h1>You left the game</h1><p>Your old seat is no longer connected to this browser.</p><div><button onClick={onCreate}><Plus size={18}/>Create game</button><button onClick={onJoin}><ArrowRight size={18}/>Join game</button></div></main>}

const CONFETTI=[['194','191','8','18','160','#FFC53D'],['1079','433','9','13','148','#2F6BFF'],['823','74','7','20','179','#FFFFFF'],['243','412','7','19','175','#FFC53D'],['1149','699','7','13','43','#7A3FBF'],['279','313','8','22','198','#2F6BFF'],['258','710','9','15','160','#FFC53D'],['443','128','7','17','278','#2F6BFF'],['152','668','8','16','86','#FFFFFF'],['334','442','10','17','145','#FFC53D'],['218','177','10','19','162','#7A3FBF'],['538','497','6','12','233','#2F6BFF'],['568','367','11','15','158','#FFC53D'],['570','205','10','17','85','#2F6BFF'],['374','557','10','13','309','#FFFFFF'],['1058','543','11','21','231','#FFC53D'],['435','270','9','12','77','#7A3FBF'],['915','207','8','19','344','#2F6BFF'],['739','329','6','16','32','#FFC53D'],['1072','431','11','17','169','#2F6BFF'],['1100','205','7','20','9','#FFFFFF'],['869','482','7','19','313','#FFC53D'],['256','46','7','20','29','#7A3FBF'],['1024','610','6','17','52','#2F6BFF'],['384','362','8','13','23','#FFC53D'],['403','573','8','14','49','#2F6BFF'],['784','80','7','12','145','#FFFFFF'],['541','26','7','17','272','#FFC53D'],['452','671','8','19','258','#7A3FBF'],['477','74','9','15','317','#2F6BFF'],['276','233','6','13','11','#FFC53D'],['498','398','9','16','326','#2F6BFF'],['200','649','9','16','238','#FFFFFF'],['846','341','8','21','348','#FFC53D']] as const;
function SequenceReveal({room,winnerId,won}:{room:RoomSnapshot;winnerId:string;won:boolean}){const sequences=room.round!.sequences.filter(s=>s.teamId===winnerId);const team=room.teams.find(t=>t.id===winnerId);const color=team?.color?COLOR_HEX[team.color]:'#2F6BFF';const highlight=won?'#FFC53D':color;const unique=new Map(sequences.flatMap(seq=>seq.cells).map(cell=>[cellKey(cell),cell]));const tag=room.teams.length===3?`${team?.color?.toUpperCase()} · ONE SEQUENCE`:won?'TWO SEQUENCES':`${team?.color?.toUpperCase()} · TWO SEQUENCES`;return <div className="sequence-reveal" aria-hidden="true" style={{'--highlight':highlight,'--highlight-text':won?'#1D1F3A':'#FFFFFF'} as React.CSSProperties}>{sequences.map(seq=>{const cells=seq.cells.map(toDisplay);const a=cells[0],b=cells[cells.length-1];const point=(c:Cell)=>({x:196.7+98.41075*c.col,y:188.85+70.79133*c.row});const p1=point(a),p2=point(b);const dx=p2.x-p1.x,dy=p2.y-p1.y;const length=Math.hypot(dx,dy)+66;const angle=Math.atan2(dy,dx)*180/Math.PI;return <div key={seq.id} className="winning-line" style={{left:(p1.x+p2.x)/2-length/2,top:(p1.y+p2.y)/2-32.5,width:length,transform:`rotate(${angle}deg)`}}/>})}{[...unique].map(([key,cell])=>{const p=toDisplay(cell);return <i key={key} style={{left:196.7+98.41075*p.col-16,top:188.85+70.79133*p.row-16,background:color}}/>})}<span className="sequence-tag"><Sparkles size={13}/>{tag}</span></div>}
function Result({room,command,onNew}:{room:RoomSnapshot;command:(x:Record<string,unknown>)=>Promise<void>;onNew:()=>void}){const winner=room.teams.find(t=>t.id===room.round?.result?.winnerTeamId);const counts=room.teams.map(team=>room.round?.sequences.filter(s=>s.teamId===team.id).length??0);const mine=room.seats.find(s=>s.id===room.yourSeatId)?.teamId;const mineTeam=room.teams.find(t=>t.id===mine);const won=winner?.id===mine;const winnerSeats=room.seats.filter(s=>s.teamId===winner?.id&&!s.computer);const partnerNames=winnerSeats.filter(s=>s.id!==room.yourSeatId).map(s=>s.name);const winnerNames=winnerSeats.map(s=>s.name);const opponent=room.teams.find(t=>t.id!==winner?.id);const opponentName=opponent?.color?`${opponent.color[0].toUpperCase()}${opponent.color.slice(1)}`:'the other team';const subtitle=!winner?'':won?(room.teams.length===3?`Three teams, first sequence wins. ${partnerNames.length?`You & ${partnerNames.join(' & ')}`:'You'} got there first.`:`${partnerNames.length?`You & ${partnerNames.join(' & ')}`:'You'} closed out two sequences to ${opponentName}'s none.`):`${winnerNames.join(' & ')||winner.color} closed out ${room.teams.length===3?'one sequence':'two sequences'} before you could answer. Here’s how.`;return <div className="result-scrim">{winner&&<SequenceReveal room={room} winnerId={winner.id} won={won}/>}<div className="confetti" aria-hidden="true">{CONFETTI.map((c,i)=><i key={i} style={{left:`${c[0]}px`,top:`${c[1]}px`,width:`${c[2]}px`,height:`${c[3]}px`,transform:`rotate(${c[4]}deg)`,background:c[5]}}/>)}</div><section className="result-bar" style={{'--team':mineTeam?.color?COLOR_HEX[mineTeam.color]:'#2F6BFF'} as React.CSSProperties}><div className="result-content"><div className="result-copy"><p className="eyebrow" style={{color:won?'#FFC53D':winner?.color?COLOR_HEX[winner.color]:undefined}}>GAME OVER · {winner?`${winner.color?.toUpperCase()} WINS`:'DRAW'}</p><h1>{winner?(won?'You win!':'You lose'):'Draw'}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="result-actions">{room.teams.length===2?<div className="result-score result-score-two"><i style={{background:room.teams[0]?.color?COLOR_HEX[room.teams[0].color!]:'#777'}}/><span>{counts[0]??0}&nbsp; — &nbsp;{counts[1]??0}</span><i style={{background:room.teams[1]?.color?COLOR_HEX[room.teams[1].color!]:'#777'}}/></div>:<div className="result-score result-score-three">{room.teams.map((team,index)=><span className="score-team" key={team.id}><i style={{background:team.color?COLOR_HEX[team.color]:'#777'}}/><b>{counts[index]??0}</b></span>)}</div>}<div><button className="new-game-btn" onClick={onNew}><Users size={18}/>New game</button><button className="replay-btn" onClick={()=>command({type:'replay'})}><RotateCcw size={18}/>Replay</button></div></div></div></section></div>}
function JoinDialog({name,onClose,onJoin}:{name:string;onClose:()=>void;onJoin:(code:string,name:string,roomId?:string)=>Promise<void>}){
  const params=new URLSearchParams(location.search);const initial=params.get('code')?.slice(0,2)??'';const inviteRoom=params.get('room')??undefined;const [code,setCode]=useState(initial);const [draftName,setDraftName]=useState(name);const [lookup,setLookup]=useState<RoomLookup|null>(null);const [error,setError]=useState('');
  useEffect(()=>{let active=true;if(code.length!==2){setLookup(null);return}api.lookup(code,inviteRoom).then(result=>active&&setLookup(result)).catch(()=>active&&setLookup({found:false}));return()=>{active=false}},[code,inviteRoom]);
  const submit=()=>{const clean=draftName.trim().replace(/\s+/g,' ');if(!clean){setError('Enter your name');return}onJoin(code,clean,inviteRoom).catch(e=>setError(e.message))};
  return <div className="scrim join-screen"><header className="join-top"><Logo/><button className="lobby-close" onClick={onClose} aria-label="Close"><X size={18}/></button></header><i className="join-chip chip-a"><span/></i><i className="join-chip chip-b"><span/></i><i className="join-chip chip-c"><span/></i><i className="join-chip chip-d"><span/></i>
    <section className="join-page" role="dialog" aria-modal="true" aria-labelledby="join-title"><p className="eyebrow">JOIN A GAME</p><i className="join-spacer"/><h2 id="join-title">Enter the game code</h2><div className="join-code-cards" onClick={()=>document.querySelector<HTMLInputElement>('.join-code-input')?.focus()}><div className="join-code-card first"><small><b>{code[0]??'–'}</b><Heart/></small><strong>{code[0]??'–'}</strong><Heart className="card-suit-bottom"/></div><div className="join-code-card second"><small><b>{code[1]??'–'}</b><Spade/></small><strong>{code[1]??'–'}</strong><Spade className="card-suit-bottom"/></div><input className="join-code-input" autoFocus inputMode="numeric" maxLength={2} value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,''));setError('')}} aria-label="Game code"/></div>
      <div className={`join-status ${lookup?.found?'found':''}`}>{lookup?.found&&<span className="join-faces">{Array.from({length:Math.min(lookup.count??0,3)},(_,index)=><i key={index} style={{'--avatar-team':COLOR_HEX[COLORS[index%COLORS.length]]} as React.CSSProperties}><img src={avatar(`avataaars-${String(index+1).padStart(2,'0')}`)} alt=""/></i>)}</span>}<span className="join-found-copy">{lookup?.found&&<Check size={16}/>}<span>{code.length!==2?'Enter your two-digit invite code':lookup?.expired?'This invite has expired.':lookup?.found?`Game found · ${lookup.count??0} ${(lookup.count??0)===1?'player':'players'} waiting`:'No game found for that code'}</span></span></div>
      <i className="join-status-spacer"/><div className="join-actions"><label><User size={18}/><input value={draftName} maxLength={24} onChange={e=>setDraftName(e.target.value)} aria-label="Your name"/></label><button disabled={code.length!==2||!lookup?.found||!lookup.joinable} onClick={submit}>Join game<ArrowRight size={20}/></button></div>{error&&<p className="error">{error}</p>}<p className="join-new">No code? <button onClick={onClose}>Start a new game</button></p>
    </section></div>
}

export function App(){
  const [room,setRoom]=useState<RoomSnapshot|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [toast,setToast]=useState('');const [join,setJoin]=useState(location.pathname.includes('/join'));const [menu,setMenu]=useState(false);const [picker,setPicker]=useState(false);const [dialog,setDialog]=useState<'rules'|'new'|'leave'|null>(null);const [pending,setPending]=useState(false);const [left,setLeft]=useState(false);const [sound,setSound]=useState(cues.enabled);const [animations,setAnimations]=useState(()=>localStorage.getItem('sequence-animations')!=='off');const previous=useRef<RoomSnapshot|null>(null);const profile=useRef({name:'Player',avatarId:'avataaars-01'});
  useEffect(()=>{let off=()=>{};api.session().then(async session=>{setRoom(session.room??await api.create(`Player ${Math.floor(Math.random()*90+10)}`,'avataaars-01'));off=connect(setRoom)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));return()=>off()},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(timer)},[toast]);
  useEffect(()=>{if(room?.phase!=='lobby')setToast('')},[room?.phase]);
  useEffect(()=>{localStorage.setItem('sequence-animations',animations?'on':'off')},[animations]);
  useEffect(()=>{const before=previous.current;previous.current=room;if(!before?.round||!room?.round||before.round.id!==room.round.id)return;if(room.round.result&&!before.round.result){const winner=room.round.result.winnerTeamId;const mine=room.seats.find(s=>s.id===room.yourSeatId)?.teamId;cues.play(winner?winner===mine?'win':'loss':'draw');return}if(room.round.lastMove?.turn!==before.round.lastMove?.turn){const made=room.round.sequences.some(s=>s.createdTurn===room.round!.lastMove?.turn);cues.play(made?'sequence':room.round.lastMove?.kind==='remove'?'remove':'place');if(room.round.currentSeatId===room.yourSeatId)setTimeout(()=>cues.play('your-turn'),made?305:110)}},[room]);
  const command=async(x:Record<string,unknown>)=>{if(!room)return;try{setError('');setRoom(await api.command(room.id,x as never))}catch(e){setError(e instanceof Error?e.message:'Something went wrong')}};
  const me=useMemo(()=>room?.seats.find(s=>s.id===room.yourSeatId),[room]);
  useEffect(()=>{if(me)profile.current={name:me.name,avatarId:me.avatarId}},[me]);
  const chooseAvatar=(id:string)=>{if(me)command({type:'profile',name:me.name,avatarId:id});setPicker(false)};
  const newGame=async()=>{setPending(true);try{const next=await api.createNew(profile.current.name,profile.current.avatarId);setRoom(next);setLeft(false);setDialog(null);setMenu(false);history.replaceState({},'', '/sequence/')}catch(e){setError(e instanceof Error?e.message:'Couldn’t create a new game')}finally{setPending(false)}};
  const leaveGame=async()=>{if(!room)return;setPending(true);try{await api.leave(room.id);setRoom(null);setLeft(true);setDialog(null);setMenu(false);history.replaceState({},'', '/sequence/')}catch(e){setError(e instanceof Error?e.message:'Couldn’t leave the game')}finally{setPending(false)}};
  if(location.pathname==='/sequence/credits'||location.pathname==='/sequence/credits/')return <Credits/>;
  if(left)return <><LeftScreen onCreate={newGame} onJoin={()=>setJoin(true)}/>{join&&<JoinDialog name={profile.current.name} onClose={()=>setJoin(false)} onJoin={async(code,name,roomId)=>{const joined=await api.join(code,name,profile.current.avatarId,roomId);setRoom(joined);setLeft(false);setJoin(false);history.replaceState({},'',`/sequence/room/${joined.id}`)}}/>}{error&&<div className="error-toast" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}</>;
  if(loading)return <Spinner/>;if(!room)return <div className="fatal"><Logo/><h1>Couldn’t open the game</h1><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div>;
  const toggleSound=async(value:boolean)=>{const accepted=await cues.setEnabled(value);setSound(accepted);if(value&&!accepted)setToast('Sound is unavailable in this browser.')};
  return <><div className={`app ${animations?'':'no-motion'}`}>{room.phase==='lobby'?<Lobby room={room} command={command} onJoin={()=>setJoin(true)} onAvatar={()=>setPicker(true)} onToast={setToast}/>:<Game room={room} command={command} menuOpen={menu} onMenu={()=>setMenu(value=>!value)} onAvatar={()=>setPicker(true)}/>}</div>{room.phase==='finished'&&<Result room={room} command={command} onNew={()=>setDialog('new')}/>} {menu&&<Menu sound={sound} setSound={toggleSound} animations={animations} setAnimations={setAnimations} onClose={()=>setMenu(false)} onNew={()=>{setMenu(false);setDialog('new')}} onRules={()=>{setMenu(false);setDialog('rules')}} onLeave={()=>{setMenu(false);setDialog('leave')}}/>} {join&&<JoinDialog name={me?.name??'Player'} onClose={()=>{setJoin(false);history.replaceState({},'',`/sequence/room/${room.id}`)}} onJoin={async(code,name,roomId)=>{const joined=await api.join(code,name,me?.avatarId??'avataaars-01',roomId);setRoom(joined);setJoin(false);history.replaceState({},'',`/sequence/room/${joined.id}`)}}/>}{picker&&me&&<AvatarPicker current={me.avatarId} onSelect={chooseAvatar} onClose={()=>setPicker(false)}/>} {dialog==='rules'&&<RulesDialog onClose={()=>setDialog(null)}/>} {(dialog==='new'||dialog==='leave')&&<ConfirmDialog kind={dialog} phase={room.phase} pending={pending} onCancel={()=>setDialog(null)} onConfirm={dialog==='new'?newGame:leaveGame}/>} {toast&&<div className="toast" role="status">{toast}</div>}{error&&<div className="error-toast" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}</>;
}
